-- Seed: 30 investigative threads for Tideline Thread Intelligence System

INSERT INTO threads (thread_number, title, category, status, horizon, hypothesis, resolution_condition, audience, connects_to) VALUES

(1, 'BBNJ Ratification Slippage', 'GOVERNANCE', 'ACTIVE', 'SHORT', 'The High Seas Treaty is not hitting its 60-ratification threshold on schedule. States are stalling through procedural delays, quiet renegotiation, or deliberate inaction.', '60 ratifications achieved, or timeline formally revised by the Secretariat.', 'Policy / NGO / Legal', '2, 3, 4'),

(2, 'ABMT Provisions: Teeth or Theatre?', 'GOVERNANCE', 'OPEN', 'MEDIUM', 'Area-Based Management Tool provisions in BBNJ are being operationalised with measures substantively weaker than the treaty text requires. States are routing around the framework via ISA and IMO.', 'First ABMT formally designated under BBNJ, with independent assessment of enforcement provisions.', 'Policy / Legal / Conservation', '1, 3, 28'),

(3, 'ISA Exploitation Code and Contractor Pipeline', 'GOVERNANCE', 'ACTIVE', 'SHORT', 'The ISA is under coordinated pressure to finalise a mining code before scientific consensus on environmental impacts is established. Sponsoring states are pushing contractor applications regardless of code status.', 'Exploitation code adopted, or ISA Council formally delays pending independent scientific review.', 'Finance / Policy / ESG', '4, 28, 29'),

(4, 'ISA Moratorium: Coalition vs Pipeline', 'GOVERNANCE', 'ACTIVE', 'SHORT', 'The moratorium coalition is growing but may not reach blocking weight before the contractor pipeline forces a code vote.', 'Formal moratorium adopted at ISA Assembly, or exploitation code approved, whichever comes first.', 'Policy / Finance / Conservation', '3, 29'),

(5, 'CITES Marine Trade Gap', 'GOVERNANCE', 'OPEN', 'MEDIUM', 'Species listed under CITES are being traded through jurisdictions applying the convention selectively. Non-Detriment Findings are functioning as a rubber stamp for commercial trade.', 'CITES CoP adopts strengthened NDF standards for marine species, or documented pattern of NDF abuse triggers formal compliance review.', 'Conservation / Legal / Policy', '14'),

(6, 'Blue Bond Credibility Gap', 'ESG', 'OPEN', 'MEDIUM', 'Blue bonds are being issued with certification frameworks insufficiently rigorous to verify ocean-positive outcomes. Some issuers are actively avoiding independent audit.', 'Standardised independently verified blue bond taxonomy adopted by ICMA or equivalent, with mandatory disclosure of use-of-proceeds at project level.', 'Finance / ESG', '8, 10'),

(7, 'Shipping ESG Disclosure vs AIS Reality', 'ESG', 'ACTIVE', 'SHORT', 'ESG disclosures from major shipping companies on emissions, routing, and speed do not match what AIS tracking data shows. The gap is material and verifiable with public data.', 'Documented discrepancy published triggering regulatory or investor response, or independent verification confirms alignment.', 'Finance / ESG / Shipping', '26'),

(8, 'TNFD and the Ocean Exclusion', 'ESG', 'OPEN', 'MEDIUM', 'TNFD-aligned disclosures by financial institutions are systematically excluding ocean dependencies and risks. Ocean is being treated as a residual category in nature-risk reporting.', 'TNFD adopts ocean-specific supplementary guidance with mandatory metrics for ocean-exposed sectors.', 'Finance / ESG', '6, 9'),

(9, 'Private Equity in Industrial Fishing', 'ESG', 'OPEN', 'LONG', 'PE-backed fishing companies are not improving practices post-acquisition. ESG-labelled funds are materially exposed to bottom-trawling and shark-finning supply chains without adequate disclosure.', 'Documented case of ESG fund holding proven IUU or destructive fishing company, or sector-wide disclosure standard adopted.', 'Finance / ESG', '8, 12'),

(10, 'Blue Carbon Credit Integrity', 'ESG', 'OPEN', 'MEDIUM', 'Blue carbon offset projects are generating credits that lack genuine additionality and permanence. Verification methodologies are being gamed by project developers.', 'VCMI or ICVCM adopts binding blue carbon methodology standards, or major voluntary market suspends blue carbon credit issuance pending review.', 'Finance / ESG / Conservation', '6'),

(11, 'PSMA Enforcement in Transhipment Ports', 'FISHERIES', 'OPEN', 'MEDIUM', 'The Port State Measures Agreement is not being meaningfully enforced in major transhipment hubs. IUU-caught fish is entering certified supply chains through ports with weak inspection regimes.', 'FAO PSMA Review Conference findings published, or documented case of IUU entry through named port triggers flag state response.', 'Legal / Policy / NGO', '12, 14'),

(12, 'MSC Certification Credibility', 'FISHERIES', 'OPEN', 'MEDIUM', 'MSC is certifying fisheries that independent stock assessments consider overfished or data-deficient. The certification process is structurally captured by commercial fishing interests.', 'MSC reforms Conformity Assessment Body accreditation, or public evidence of systematic certification failure triggers retailer withdrawal from scheme.', 'NGO / Policy / Retail', '9, 11'),

(13, 'EUDR Ocean Blind Spot', 'FISHERIES', 'OPEN', 'MEDIUM', 'The EU Deforestation Regulation creates a perverse incentive to shift demand toward ocean-sourced protein from supply chains with no equivalent deforestation-linked regulation.', 'European Commission publishes assessment of EUDR demand substitution effects on marine fisheries, or equivalent regulatory gap formally acknowledged.', 'Policy / NGO / ESG', '11, 20'),

(14, 'China DWF and Supply Chain Laundering', 'FISHERIES', 'OPEN', 'LONG', 'Vessels flagged under Chinese companies or proxies are using re-flagging, transhipment, and obscured ownership to launder IUU catch into certified supply chains.', 'Documented ownership chain linking IUU catch to certified retailer, or flag state registry reform closes specific loophole.', 'Legal / Policy / NGO', '5, 11'),

(15, 'Seafood Species Substitution at Retail', 'FISHERIES', 'OPEN', 'SHORT', 'DNA testing of seafood sold in UK and EU retail chains shows species substitution at material rates. Retailer response to prior findings has been inadequate.', 'Systematic DNA audit published by enforcement authority, or retailer commits to mandatory species verification across supply chain.', 'Policy / NGO / Retail', '12'),

(16, 'Ocean Heat and Insurance Exposure', 'CLIMATE', 'OPEN', 'MEDIUM', 'The rate of ocean heat accumulation is not being incorporated into actuarial models for coastal property, marine infrastructure, and fisheries insurance. Insurers are systemically underpricing climate-linked ocean risk.', 'Lloyd''s or equivalent publishes ocean heat content as a mandatory factor in marine and coastal property underwriting models.', 'Finance / ESG / Policy', '19'),

(17, 'AMOC Monitoring Gap', 'CLIMATE', 'ACTIVE', 'SHORT', 'The Atlantic Meridional Overturning Circulation monitoring network is inadequate to detect tipping-point signals with sufficient lead time. The RAPID array funding is insecure under current US federal science budget pressure.', 'RAPID array funding secured through 2030, or international alternative monitoring arrangement formalised.', 'Science / Policy / Finance', '16'),

(18, 'Trawling Carbon Release and Lobbying', 'CLIMATE', 'OPEN', 'MEDIUM', 'The science on bottom trawling releasing seabed carbon is robust enough to support regulatory action. Methodological disputes are being funded or amplified by fishing industry lobbyists to manufacture delay.', 'IPCC or equivalent body endorses seabed carbon release estimates with sufficient confidence for regulatory use, or specific lobbying funding chain documented.', 'Science / Policy / NGO', '30'),

(19, 'Ocean Acidification and Shellfish Losses', 'CLIMATE', 'OPEN', 'MEDIUM', 'Commercial shellfish producers in the North Atlantic and Pacific Northwest are experiencing measurable production losses attributable to acidification. These losses are not being disclosed to investors.', 'Industry body publishes verified production loss data linked to acidification, or investor disclosure case triggers regulatory guidance.', 'Science / Finance / ESG', '16'),

(20, 'Plastics Treaty Ocean Provisions Weakening', 'CLIMATE', 'ACTIVE', 'SHORT', 'The Global Plastics Treaty in its current negotiating trajectory will not contain enforceable provisions that materially reduce ocean plastic loads. The text is being weakened by petrochemical state blocs.', 'Treaty adopted with binding production reduction targets and traceable ocean-pathway provisions, or adopted without them.', 'Policy / NGO / ESG', '13'),

(21, 'NOAA Vessel Speed Rule Compliance vs Reality', 'CETACEANS', 'ACTIVE', 'SHORT', 'NOAA vessel speed rule compliance calculations overstate strike risk reduction. The rule as applied is not materially reducing North Atlantic right whale mortality.', 'NOAA publishes independent vessel strike model with transparent methodology, or NARW population trend reverses.', 'Conservation / Legal / Policy', '28'),

(22, 'Whaling Coalition Durability', 'CETACEANS', 'OPEN', 'LONG', 'The Japan-Iceland-Norway whaling coalition is under pressure from ESG investor scrutiny, domestic consumer trends, and changing political economy. It may fracture before a formal IWC resolution.', 'One of the three states suspends commercial whaling operations, or IWC achieves binding resolution on commercial whaling.', 'Conservation / Policy / Finance', '5'),

(23, 'EU Cetacean Bycatch Enforcement Gap', 'CETACEANS', 'ACTIVE', 'SHORT', 'EU emergency measures on cetacean bycatch are not being enforced uniformly at member state level. France and Spain are applying them selectively.', 'European Commission launches infringement proceedings against member state, or independent observer data published showing systematic under-reporting.', 'Conservation / Legal / Policy', '28'),

(24, 'Live Cetacean Trade via Legal Grey Zones', 'CETACEANS', 'OPEN', 'MEDIUM', 'Live capture and export of dolphins and small whales from non-IWC states is being facilitated by gaps in CITES appendix listings. Gulf state and Southeast Asian facilities are primary destinations.', 'CITES CoP lists targeted small cetacean species under Appendix I, or specific capture operation documented and suspended.', 'Conservation / Legal', '5'),

(25, 'UK Captive Cetacean Policy Substance vs Optics', 'CETACEANS', 'OPEN', 'MEDIUM', 'The Animals (Sentience) Act and related UK legislation are not translating into concrete cetacean display or import policy. Government is managing political optics without substantive regulatory change.', 'UK government publishes enforceable regulations on cetacean display import standards, or formally declines to do so.', 'Conservation / Policy / Legal', '24'),

(26, 'IMO GHG Ambition vs Enforcement Architecture', 'REGULATORY', 'ACTIVE', 'MEDIUM', 'The IMO 2023 revised GHG strategy has no enforcement architecture capable of delivering net-zero by 2050. The CII rating system is being applied inconsistently by flag states.', 'IMO MEPC adopts binding mid-term measure with independent verification mechanism, or CII compliance data published showing systematic flag state divergence.', 'Shipping / ESG / Policy', '7'),

(27, 'Revolving Door Ocean Regulators to Industry', 'REGULATORY', 'OPEN', 'LONG', 'Senior figures from NOAA, ISA, IMO, and national fisheries bodies are moving into industry roles raising regulatory capture concerns. Disclosure requirements are not being consistently met.', 'Documented case of regulatory decision materially benefiting a former official''s subsequent employer within standard cooling-off period.', 'Policy / NGO / Legal', '28'),

(28, 'FOI Resistance in Ocean Governance Bodies', 'REGULATORY', 'ACTIVE', 'STRUCTURAL', 'The ISA, IWC, and IMO are using intergovernmental status to resist disclosure that equivalent national bodies would be required to provide. This creates a structural transparency gap enabling other failures.', 'This thread does not resolve. It accumulates evidence that feeds other threads.', 'All segments', '2, 3, 21, 23, 27, 29'),

(29, 'ISA EIAs Independent Review or Rubber Stamp', 'REGULATORY', 'OPEN', 'MEDIUM', 'Environmental Impact Assessments filed with the ISA for exploration licences are not being independently reviewed. Key data is being withheld as commercially confidential, preventing scientific scrutiny.', 'ISA Legal and Technical Commission publishes EIA review methodology with independent scientific panel, or specific EIA data withheld from public access documented.', 'Science / Policy / Legal', '3, 4, 28'),

(30, '30x30 Real Protection or Paper Parks', 'REGULATORY', 'ACTIVE', 'MEDIUM', 'Kunming-Montreal 30x30 marine commitments are being met through MPA designations in low-commercial-value areas. States are gaming the target without constraining industry.', 'Independent assessment published showing MPA designation quality, or specific state challenged on MPA ecological coverage at CBD review.', 'Conservation / Policy / ESG', '2, 18');
