/**
 * Synthetic end-to-end test for the entity-matching → project_auto_entries auto-attach pipeline.
 *
 * Usage:
 *   npx @dotenvx/dotenvx run -f .env.local -- npx tsx scripts/test-auto-attach.ts
 *
 * What it does:
 *   1. Inserts a synthetic story whose title + summary name all three tracked entities
 *   2. Calls matchEntitiesToStory() (live, not dryRun)
 *   3. Queries entity_mentions and project_auto_entries for the story
 *   4. Prints PASS / FAIL
 *   5. Prints cleanup SQL (NOT executed automatically)
 */

import { createClient } from "@supabase/supabase-js";
import { randomUUID } from "crypto";
import { matchEntitiesToStory } from "../lib/entity-matching";

const PROJECT_ID = "71243f6a-6bf7-4b70-a9db-2817e8ef7b9c";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

const SUMMARY =
  "A synthetic test story mentioning BBNJ Agreement, ISA Secretariat, and International Whaling Commission " +
  "for end-to-end verification of the entity-matching auto-attach pipeline. Generated by scripts/test-auto-attach.ts.";

async function main() {
  console.log("══════════════════════════════════════════════════════════");
  console.log("  Synthetic Auto-Attach Test");
  console.log("  Target project:", PROJECT_ID);
  console.log("══════════════════════════════════════════════════════════\n");

  // ── Step 1: Insert synthetic story ──────────────────────────────────────────
  const syntheticLink = `https://test.thetideline.co/synthetic-${randomUUID()}`;

  console.log("Step 1 — Inserting synthetic story...");
  const { data: inserted, error: insertErr } = await supabase
    .from("stories")
    .insert({
      title: "[TEST-AUTH] BBNJ Agreement implementation milestone reached at IWC sidelines",
      link: syntheticLink,
      source_name: "Tideline Test Harness",
      topic: "bbnj",
      source_type: "test",
      published_at: new Date().toISOString(),
      short_summary: SUMMARY,
      description: SUMMARY,
      entities_extracted: false,
    })
    .select("id, title")
    .single();

  if (insertErr || !inserted) {
    console.error("FAILED to insert story:", insertErr?.message);
    process.exit(1);
  }

  const storyId = inserted.id;
  console.log("  ✓ Story inserted:", storyId);
  console.log("  Title:", inserted.title, "\n");

  // ── Step 2: Run entity matching ──────────────────────────────────────────────
  console.log("Step 2 — Running matchEntitiesToStory()...");
  const matchResult = await matchEntitiesToStory(storyId);
  console.log("  Match result:", JSON.stringify(matchResult, null, 2), "\n");

  // ── Step 3a: Verify entity_mentions ─────────────────────────────────────────
  console.log("Step 3a — Querying entity_mentions...");
  const { data: mentions, error: mentionErr } = await supabase
    .from("entity_mentions")
    .select("story_id, entity_id, match_method, confidence")
    .eq("story_id", storyId);

  if (mentionErr) {
    console.error("  entity_mentions query failed:", mentionErr.message);
  } else {
    console.log(`  ${mentions?.length ?? 0} mention(s) written:`);
    for (const m of mentions ?? []) {
      console.log(`    entity_id=${m.entity_id}  method=${m.match_method}  confidence=${m.confidence}`);
    }
  }
  console.log();

  // ── Step 3b: Verify project_auto_entries (load-bearing check) ───────────────
  console.log("Step 3b — Querying project_auto_entries...");
  let { data: entries, error: entriesErr } = await supabase
    .from("project_auto_entries")
    .select(`
      id,
      project_id,
      entry_type,
      matched_entity_id,
      entities ( name ),
      projects ( name )
    `)
    .eq("story_id", storyId);

  // If PostgREST schema cache hasn't refreshed yet, the FK join on matched_entity_id
  // may fail with a relationship error. Fall back to a flat query — PASS/FAIL is unaffected.
  if (entriesErr) {
    console.warn("  Joined query failed, falling back to flat query:", entriesErr.message);
    const flat = await supabase
      .from("project_auto_entries")
      .select("id, project_id, entry_type, matched_entity_id")
      .eq("story_id", storyId);
    entries = flat.data;
    entriesErr = flat.error;
  }

  if (entriesErr) {
    console.error("  project_auto_entries query failed:", entriesErr.message);
  } else {
    console.log(`  ${entries?.length ?? 0} auto-entry row(s) written:`);
    for (const e of entries ?? []) {
      const entityName = (e as { entities?: { name: string } | null }).entities?.name ?? "(name unavailable)";
      const projectName = (e as { projects?: { name: string } | null }).projects?.name ?? "(name unavailable)";
      console.log(
        `    project_id=${e.project_id}  project="${projectName}"  entry_type=${e.entry_type}  matched_entity_id=${e.matched_entity_id}  matched_entity="${entityName}"`
      );
    }
  }
  console.log();

  // ── Step 4: PASS / FAIL ──────────────────────────────────────────────────────
  const autoEntries = entries ?? [];
  const hasAutoAttach =
    autoEntries.length > 0 &&
    autoEntries.some(
      (e) => e.project_id === PROJECT_ID && e.matched_entity_id !== null
    );

  if (hasAutoAttach) {
    console.log("══════════════════════════════════════════════════════════");
    console.log("  ✅  PASS — project_auto_entries row written with matched_entity_id");
    console.log("══════════════════════════════════════════════════════════\n");
  } else {
    console.log("══════════════════════════════════════════════════════════");
    console.log("  ❌  FAIL — no project_auto_entries row for this project with matched_entity_id");
    console.log("     Check: does project_entities contain rows for project", PROJECT_ID, "?");
    console.log("══════════════════════════════════════════════════════════\n");
  }

  // ── Step 5: Cleanup SQL (printed only, not executed) ─────────────────────────
  console.log("Cleanup SQL (run manually in Studio after reviewing results):");
  console.log("─────────────────────────────────────────────────────────");
  console.log(`DELETE FROM project_auto_entries WHERE story_id = '${storyId}';`);
  console.log(`DELETE FROM entity_mentions WHERE story_id = '${storyId}';`);
  console.log(`DELETE FROM stories WHERE id = '${storyId}';`);
  console.log("─────────────────────────────────────────────────────────");
}

main().catch((err) => {
  console.error("Unhandled error:", err);
  process.exit(1);
});
