CREATE TABLE IF NOT EXISTS survey_responses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT now(),
  role text,
  role_other text,
  procurement text,
  time_spent text,
  current_sources text[],
  hardest_to_track text[],
  biggest_pain text,
  feed_value int,
  brief_value int,
  tracker_value int,
  workspace_value int,
  meeting_prep_value int,
  entity_alerts_value int,
  contradiction_value text,
  report_value text,
  linkedin_value text,
  calendar_value text,
  alerts_value text,
  price text,
  missing text
);
